# Temporary deployment stuff.
# Passwords in this file SHOULD BE CHANGED.
version: '3.7'

services:
  tsdb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: saerro321
      POSTGRES_USER: saerrouser
      POSTGRES_DB: data
    ports:
      - 5432

  api:
    image: ghcr.io/genudine/saerro/api:latest
    pull_policy: always
    ports:
      - 8000:80
    links:
      - tsdb
    restart: always
    environment:
      DATABASE_ADDR: postgres://saerrouser:saerro321@tsdb:5432/data

  ws:
    image: ghcr.io/genudine/saerro/websocket:latest
    pull_policy: always
    restart: always
    ports:
      - 8999:8999
    environment:
      DATABASE_ADDR: postgres://saerrouser:saerro321@tsdb:5432/data
      WS_ADDR: wss://push.nanite-systems.net/streaming?environment=all&service-id=s:saegd
      WORLDS: all
    links:
      - tsdb

  task_prune:
    image: ghcr.io/genudine/saerro/tasks:latest
    command: /app prune
    pull_policy: always
    restart: "no"
    environment:
      DATABASE_ADDR: postgres://saerrouser:saerro321@tsdb:5432/data
    links:
      - tsdb
