# Temporary deployment stuff.
# Passwords in this file SHOULD BE CHANGED.
version: '3.7'

services:
  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  tsdb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: saerro321
      POSTGRES_USER: saerrouser
      POSTGRES_DB: data
    ports:
      - 5432

  api:
    image: ghcr.io/genudine/saerro/api:latest
    pull_policy: always
    ports:
      - 8000:80
    links:
      - tsdb
    restart: always
    environment:
      DATABASE_ADDR: postgres://saerrouser:saerro321@tsdb:$TSDB_PORT/data

  ws:
    image: ghcr.io/genudine/saerro/websocket:latest
    pull_policy: always
    restart: always
    environment:
      DATABASE_ADDR: postgres://saerrouser:saerro321@tsdb:$TSDB_PORT/data
      WS_ADDR: wss://push.nanite-systems.net/streaming?environment=ps2&service-id=s:saegd
      WORLDS: all
    links:
      - tsdb
