[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.22.1", default_features = false, features = ["r2d2"] }
lazy_static = "1.4.0"
tokio-tungstenite = { version = "0.17.2", features=["native-tls"] }
serde_json = "1.0.89"
serde = { version = "1.0.148", features = ["derive"] }
tokio = { version = "1.22.0" }
url = "2.3.1"
futures-util = "0.3.25"
futures = "0.3.25"
