[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde_json = "1.0.88"
serde = "1.0.147"
redis = { version = "0.22.1", default_features = false, features = [] }
once_cell = "1.16.0"