[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.22.1", features = ["aio", "r2d2", "tokio-comp"] }
serde_json = "1.0.88"
serde = "1.0.147"
async-graphql = { version = "4.0.16", features = ["apollo_tracing"] }
async-graphql-axum = "4.0.16"
axum = "0.6.0"
tokio = { version = "1.22.0" }
tower-http = { version = "0.3.4", features = ["cors"] }
lazy_static = "1.4.0"